[project]
name = "data-generation-api-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.1.3",
    "faker>=33.1.0",
    "fastapi[standard]>=0.115.6",
    "pydantic>=2.10.3",
    "sqlalchemy>=2.0.36",
]
